site_name: PySwiftKit Demo
site_description: Swift to Python API Generator Demo

theme:
  name: readthedocs

plugins:
  - search
  - pyswiftkit_demo:
      wasm_path: demo

markdown_extensions:
  - admonition
  - codehilite

nav:
  - Home: index.md
  - Interactive Demos:
    - Multi-Tool Demo: demo.md
    - Swift to Python: swift-to-python.md
    - Python to Swift: python-to-swift.md
    - Python DataModel: python-datamodel.md
    - KV AST Tree: kv-ast-tree.md
    - KV to SwiftUI: kv-swiftui.md
    - KV to DataModel: kv-datamodel.md
    - KV to Python Classes: kv-to-pyclass.md
